# Generated by Django 6.1 on 2026-08-23 01:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='codigo',
        ),
        migrations.AlterField(
            model_name='alumno',
            name='cedula',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.CreateModel(
            name='TarjetaRFID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=50, unique=True)),
                ('activa', models.BooleanField(default=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarjetas', to='asistencia.alumno')),
            ],
        ),
    ]
