# Generated by Django 6.1 on 2026-08-30 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0002_remove_alumno_codigo_alter_alumno_cedula_tarjetarfid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarjetarfid',
            name='alumno',
        ),
        migrations.AlterModelOptions(
            name='alumno',
            options={'ordering': ['nombre'], 'verbose_name': 'Alumno', 'verbose_name_plural': 'Alumnos'},
        ),
        migrations.AlterModelOptions(
            name='asistencia',
            options={'ordering': ['-fecha', '-hora'], 'verbose_name': 'Asistencia', 'verbose_name_plural': 'Asistencias'},
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='apellido',
        ),
        migrations.AddField(
            model_name='alumno',
            name='uid_rfid',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='UID RFID'),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='estado',
            field=models.CharField(default='presente', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='cedula',
            field=models.CharField(max_length=20, unique=True, verbose_name='Cédula'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='curso',
            field=models.CharField(max_length=50, verbose_name='Curso'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='nombre',
            field=models.CharField(max_length=150, verbose_name='Nombre y apellido'),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='asistencia.alumno', verbose_name='Alumno'),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='fecha',
            field=models.DateField(verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='hora',
            field=models.TimeField(verbose_name='Hora'),
        ),
        migrations.AddConstraint(
            model_name='asistencia',
            constraint=models.UniqueConstraint(fields=('alumno', 'fecha'), name='asistencia_unica_por_dia'),
        ),
        migrations.DeleteModel(
            name='TarjetaRFID',
        ),
    ]
