# Generated by Django 6.1 on 2026-08-30 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0003_remove_tarjetarfid_alumno_alter_alumno_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Materia',
                'verbose_name_plural': 'Materias',
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterModelOptions(
            name='alumno',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='asistencia',
            name='asistencia_unica_por_dia',
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='cedula',
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='curso',
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='uid_rfid',
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='asistencia.alumno'),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='fecha',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='hora',
            field=models.TimeField(),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='materia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asistencias', to='asistencia.materia'),
        ),
        migrations.RemoveField(
            model_name='asistencia',
            name='estado',
        ),
    ]
