# Generated by Django 6.1 on 2026-08-30 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0004_materia_alter_alumno_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaseActiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activa', models.BooleanField(default=True)),
                ('iniciada', models.DateTimeField(auto_now_add=True)),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clases_activas', to='asistencia.materia')),
            ],
            options={
                'verbose_name': 'Clase activa',
                'verbose_name_plural': 'Clases activas',
                'ordering': ['-iniciada'],
            },
        ),
    ]
